旧金山湾区除了那些出名的景点外，还有很多好玩的水上运动。比如风帆
（Windsurfing），风筝冲浪（Kiteboarding），冲浪（Surfing） 和帆船
（Sailing）。这些运动和其他活动不同，都需要经过学习才能开始享受运动带来
的乐趣。不过这些运动从岸上欣赏也挺不错的。

* 风帆(Windsurfing)

** 地点
*** Foster City

Foster City 的湖是最适合没有任何经验初学者。这里湖面平静，没有浪，风也
很小。 在这里可以体验一下 Windsurfing 的感觉，如果发现自己喜欢这种感觉，
可以到其他更好的地方去学习。

http://californiawindsurfing.com/

这里提供初学者的课程，会教一些基本知识。基本上可以让你对Windsurfing 有
个了解。如果是这真正要学习，还得去其他地方找更专业的人来教。
*** San Mateo - Coyote Point Park

San Mateo Coyote Point Park 是一个当你晋级到中级水平的时候一个理想地点。
这里水面开阔，常年有风，有一些小浪，但是不至于对windsurfing 造成太大困
难。如果浪太大，掉到水里重新起来的难度大很多。

Board Sports School http://boardsportsschool.com/ 

提供设备出租和课程。不过不建议在这里上课，这里的条件不太适合初学者。
*** ALAMEDA – Crown Beach Park 

Board Sports School 在这里也提供课程，这里水面比San Mateo 平静，比较适
合初学者。尤其是3-5月份，风向比较好而且比较稳定。到了夏季风就比较小。对
于windsurfing 问题不大。总的来说是很理想的学习的地方。
*** Berkeley - Cal Saling Club

这是一个非营利性机构，主要运营靠志愿者，如果你有很多的时间，这里是你不
二的选择。三个月才要$99 的会员费，同时加上几个小时的义工要求。你可以免
费使用所有的器材，当然有些器材使用需要相应的水平。每周六他们有针对会员
的专门课程。

如果你还没有想好，可以参加他们的open house，每个月有一个周日是open
house，他们提供免费的课程，包括所有的设备使用，甚至还有免费BBQ。

